name: "Build"

on:
  pull_request:
    paths:
      - 'eng/**'
      - 'src/**'

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: |
          az bicep build \
            --file ./src/main.bicep
